services:
  module-handbook:
    environment:
      - RAILS_ENV=test
      - SELENIUM_REMOTE_HOST=selenium-standalone
      - SELENIUM_REMOTE_PORT=4444
      - PARALLEL_WORKERS=1
# export SELENIUM_REMOTE_HOST=selenium-standalone
# export SELENIUM_REMOTE_HOST=localhost
# export SELENIUM_REMOTE_PORT=4444
# echo $SELENIUM_REMOTE_HOST && echo $SELENIUM_REMOTE_PORT
 
  selenium-standalone:
    platform: linux/x86_64/v8
    # see https://hub.docker.com/r/selenium/standalone-chrome
    # https://github.com/SeleniumHQ/docker-selenium
    image: selenium/standalone-firefox:4.24.0-20240830
    # chrome and chromium do not work on mac os
    #image: selenium/standalone-chrome:latest
    #image: selenium/standalone-chromium:latest
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2g
    ulimits:
      nofile:
        soft: 32768
        hard: 32768

