services:

  module-handbook-postgres:
    container_name: modulehandbook-database
    image: postgres:13.4-alpine
    #    container_name: module-handbook-postgres
    environment:
      - APPLICATION=module-handbook
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_USER=modhand
      - POSTGRES_DB=modhand-db-prod
      # https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
      - POSTGRES_HOST_AUTH_METHOD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

  module-handbook-exporter:
    image: ghcr.io/modulehandbook/exporter:${TAG_MODULE_HANDBOOK_EXPORTER}
    container_name: modulehandbook-exporter
    restart: always

  module-handbook:
    env_file:
      - path: ./secrets/env/active.env
    image: ghcr.io/modulehandbook/modulehandbook:${TAG_MODULE_HANDBOOK}
    container_name: modulehandbook

    environment:
      - RAILS_DB_HOST="module-handbook-postgres"
      - POSTGRES_USER=modhand
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_DB=modhand-db-prod
      - RAILS_SERVE_STATIC_FILES=true
      - EXPORTER_BASE_URL=${EXPORTER_BASE_URL:-http://module-handbook-exporter:3030/}
      - TZ=Europe/Berlin
      - EDITOR=vi

    depends_on:
      - module-handbook-postgres
      - module-handbook-exporter
    volumes:
      - ./container_logs:/module-handbook/log
      - ./secrets:/module-handbook/secrets
    restart: always

  nginx:
     env_file:
         - path: ./secrets/env/active.env
     image: nginx:latest
     container_name: reverse_proxy
     volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/templates:/etc/nginx/templates
         - ./container_logs/nginx:/var/log/nginx
         - ./secrets/nginx:/etc/ssl
     ports:
         - "80:80"
         - "443:443"
     environment:
        - NGINX_CERT_DIR=/etc/ssl
        - NGINX_PORT=80
        - NGINX_SSL_PORT=443
        - NGINX_PROXY=http://module-handbook:3000
        - NGINX_ENTRYPOINT_QUIET_LOGS=1
     depends_on:
         - module-handbook
     restart: always
