# overrides for local usage & development -
# ------------------------------------------------
# ** don't ever copy to production machine! **
# ------------------------------------------------

# see doc: https://docs.docker.com/compose/compose-file/compose-file-v3/
# override precedence:
# https://docs.docker.com/compose/extends/#adding-and-overriding-configuration

services:
  module-handbook-postgres:
    platform: linux/arm64/v8
    container_name: module-handbook-postgres
    environment:
      - POSTGRES_DB=modhand-db-dev
    ports:
     - "5432:5432" # don't do this on production!
  module-handbook:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: modhand-dev
    image: mh-local-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/module-handbook  # use app files from host
      - /module-handbook/node_modules # but not the node_modules
    environment:
      - POSTGRES_DB=modhand-db-dev
      - RAILS_ENV=development
      - CHROME_URL=http://localhost:4444/wd/hub
    restart: "no"
  chrome-server:
    platform: linux/x86_64
    image: selenium/standalone-chrome:128.0
    ports:
      - 4444:4444
      - 7900:7900
