services:
  module-handbook:    
    build:
      context: .
      dockerfile: Dockerfile
      target: modhand-prod
      args:
         RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    image: mh-local-build
    entrypoint: entrypoints/keep-open.sh
    env_file: "secrets/env/staging.env"

  #  build:
  #    context: .
  #    target: "modhand-prod"
  #    args:
  #      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}


#     image: mh-prod
# >docker build . --target modhand-prod -t mh-prod