.RECIPEPREFIX = -
start:
- sudo docker-compose up -d

stop: down
down:
- sudo docker-compose down

bash:
-  docker-compose exec module-handbook bash
bash_db:
-  docker-compose exec module-handbook-postgres bash
bash_exp:
-  docker-compose exec module-handbook-exporter bash

rails-c:
- docker exec -it modulehandbook bin/rails c

mk:
- echo $RAILS_MASTER_KEY


clean_logs:
- sudo rm container_logs/nginx/error.log container_logs/nginx/access.log container_logs/production.log
