start:
  docker-compose up -D
bash:
  docker-compose exec module-handbook bash
bash_db:
  docker-compose exec module-handbook-postgres bash
bash_exp:
  docker-compose exec module-handbook-exporter bash
stop: down
down:
  docker-compose down
