name: Tag & Label

description: 'get docker metadata depending on build stage'
inputs:
  stage:
    required: true
    type: string
outputs:
  tags:
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - run: echo stage ${{ inputs.stage }}
      shell: bash
    - run: echo repo ${{ inputs.registry }}/${{ inputs.image_name }}
      shell: bash
    - name: staging
    - name: release
    - name: pull-request
      if: ${{ inputs.stage == 'pull_request' }}

    - name: Assert
      if: ${{ inputs.stage == 'pull_request' && ! (github.event_name == 'pull_request') }}
      run: |
        echo "input {{ inputs.pull_request}} and event_name {{ github.event_name }} do not match!"
        exit 4711
      shell: bash


outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
