name: test on docker
# this is wip; container should be built only once / incrementally
# for test and deployment.

on:
  push:
    branch:
      - main
      - try_cuprite_driver

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "modulehandbook/modulehandbook"
  RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}



jobs:
  test-and-push-image:
    name: Test on Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Base Image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: modhand-base
          push: false
          tags: modhand-base:latest
      - name: Build Test Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.testci
          target: modhand-testci
          push: false
          tags: modhand-testci:latest

      - name: test in modhand-testci
        run: docker-compose -f docker-compose.testci.yml up -d
      - run: docker ps
      - run: docker exec modulehandbook-testci rails db:drop RAILS_ENV=test
      - run: docker exec modulehandbook-testci rails db:create RAILS_ENV=test
      - run: docker exec modulehandbook-testci rails db:migrate RAILS_ENV=test
      - run: docker exec modulehandbook-testci rails test
      - run: docker exec modulehandbook-testci rails test:system

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.sha.outputs.sha_short }}

      - name: Extract metadata (tags, labels) for Docker - PR
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Metadata Results
        run: |
           echo "---- tags:\n ${{ steps.meta.outputs.tags }}"
           echo "---- labels:\n ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: modhand-prod
          build-args: RAILS_MASTER_KEY=${{ secrets.rails_master_key }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
