
name: Production Deployment
on:
  workflow_call:
  inputs:     
    version:
      required: true
      type: string


jobs:
  trigger-staging:
    name: "Tryout"
    uses: ./.github/workflows/pipeline_05_deploy.yml
    with:
      version: ${{ inputs.version }}
      environment: 'production'
    secrets:
      ssh_user: ${{ secrets.DEPLOY_USER_PRODUCTION }}
      ssh_key: ${{ secrets.DEPLOY_KEY_PRODUCTION }}
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY_PRODUCTION }}
