name: docker-compose

on:
    push:
        branches:
          - main
          - dev_prod_parity

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo code
          uses: actions/checkout@v4

        - name: start container
          run: |
            docker-compose up -d
            docker ps

        - name: test
          run: |
            docker-compose exec -t module-handbook bin/rails test

        - name: system test
          run: |
            docker-compose exec -tmodule-handbook bin/rails test:system
           
