name: Build and Push Docker (NEW)

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
# -------------------------------------------------------------
# Pull Request
# -------------------------------------------------------------

      - name: Extract metadata (tags, labels) for Docker - PR
        if: ${{ github.event_name == 'pull_request' }}
        id: meta_pr
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=ref,event=pr
      - name: Build and push Docker image - PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta_pr.outputs.tags }}
          labels: ${{ steps.meta_pr.outputs.labels }}
# -------------------------------------------------------------
# Staging
# -------------------------------------------------------------

      - name: Extract metadata (tags, labels) for Docker - Staging
        if: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/master'}}
        id: meta_staging
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha
      - name: Build and push Docker image - Staging
        if: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/master'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: "modhand-prod"
          buildArgs:
            rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
          tags: ${{ steps.meta_staging.outputs.tags }}
          labels: ${{ steps.meta_staging.outputs.labels }}
# -------------------------------------------------------------
# Tag / Production
# -------------------------------------------------------------

      - name: Extract metadata (tags, labels) for Docker - Production
        if: ${{ github.ref_type == 'tag' }}
        id: meta_production
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=ref,event=tag
      - name: Build and push Docker image - Production
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          target:
          tags: ${{ steps.meta_production.outputs.tags }}
          labels: ${{ steps.meta_production.outputs.labels }}
