name: docker-compose

on:
    push:
        branches:
          - main
          - dev_prod_parity

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo code
          uses: actions/checkout@v4

        - name: start container
          run: |
            docker-compose up -d
            docker ps

        - name: test db setup
          run: |
              docker exec module-handbook rails db:drop RAILS_ENV=test
              docker exec module-handbook rails db:create RAILS_ENV=test
              docker exec module-handbook rails db:migrate RAILS_ENV=test
      
        - name: run tests with docker-compose
          run: |
            docker-compose exec -t module-handbook bin/rails test
            docker-compose exec -t module-handbook bin/rails test:system

       

        - name: run tests
          run: docker exec -t modulehandbook bin/rails test
           
        - name: run system tests
          run: |
            run: docker exec -t modulehandbook bin/rails test:system
            