name: Echo Tag and Label

on:
  push:
    branches: [  master, dryaction ]
    tags:
      - '*'
  pull_request:
    branches: [ master, main, dry-gh-action ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  echo-label:
    name: Echo Label
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: ls -a
        run: |
          echo "--------  worflows"
          ls -lart .github/actions
      - name: Call Tag Action
        # the `uses' attribute must be a path, a Docker image, or owner/repo@ref
        uses: ./.github/actions/tag_and_label
        with:
          stage: pull_request
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
        id: meta_for_all
      - name: Echo Result
        run: |
          echo "tags: ${{ steps.meta_for_all.outputs.tags }}"
          echo "labels: ${{ steps.meta_for_all.outputs.labels }}"
