
name: "M A"
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - run: 
      - name: Deploy
        run: echo "Deploy to  ${{ inputs.environment }}"
