
name: "Main"
on:
  workflow_call:
    inputs:
      deploy-to:
        type: string
        required: true
    
jobs:
  consume-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(inputs.deploy-to) }}
    uses: ./.github/workflows/matrix_03_deploy_all.yml
    with:
      environment: ${{ matrix.environment }}
      version: 'sha-fb8b096'
