name: Deploy to Production

on:
    workflow_call:  # Triggered by the Build and Push workflow
      secrets:
        rails_master_key:
          required: true
        DEPLOY_MH_KEY: 
          required: true
        DEPLOY_MH_USER: 
          required: true
        DEPLOY_MHIMI_KEY: 
          required: true
        DEPLOY_MHIMI_USER: 
          required: true
      

jobs:
    deploy-production:
        name: "Deploy module-handbook"
        runs-on: ubuntu-latest
        env:
          SSH_KEY: ${{ secrets.DEPLOY_MH_KEY }}
          SSH_USER: ${{ secrets.DEPLOY_MH_USER }}
          SSH_HOST: 'module-handbook.f4.htw-berlin.de'
          KNOWN_HOST: 'module-handbook.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEo5BCmDcatOwixOtx2GCrtNbMFzBtOHjeh9+isNrf9'
          ENV_NAME: 'imi-production' 
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ env.SSH_KEY }}
            
            - name: Verify SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"
              
            - name: Set Environment Variables
              run: |
                echo "RAILS_MASTER_KEY=${{ secrets.rails_master_key }}" >> $GITHUB_ENV

            - name: Execute Deployment
              run: |
                chmod +x deploy/production.sh
                ./deploy/production.sh ${{ env.ENV_NAME }}

   