name: Deploy to Staging

on:
    workflow_run:
        workflows: ["04: Pipeline Step Build and Push Image"]
        types:
          - completed

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
            SSH_KEY: ${{ secrets.DEPLOY_MH_STAG_KEY }}
            SSH_USER: ${{ secrets.DEPLOY_MH_STAG_USER }}
            SSH_HOST: 'module-handbook-staging.f4.htw-berlin.de'
            KNOWN_HOST: 'module-handbook-staging.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEo5BCmDcatOwixOtx2GCrtNbMFzBtOHjeh9+isNrf9'
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ env.SSH_KEY }}
            
            - name: Verify SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"
              
            - name: Set Environment Variables
              run: |
                echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY_STAGING }}" >> $GITHUB_ENV

            - name: Execute Deployment
              run: |
                chmod +x deploy/staging.sh
                ./deploy/staging.sh
  