name: Deploy

on:
    workflow_call:  # Triggered by the 02: Pipeline Structure workflow
      inputs:     
        version:
          required: true
          type: string
        environment:
          required: true
          type: string




jobs:

    deploy-gen:
        runs-on: ubuntu-latest
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}

        steps:
            - name: Generate Secret names
              run: |
                # SN: Secret name
                SN_DEPLOY_KEY="$(echo DEPLOY_KEY_${{ inputs.environment }} | tr '[:lower:]' '[:upper:]')"
                SN_DEPLOY_USER="$(echo DEPLOY_USER_${{ inputs.environment }} | tr '[:lower:]' '[:upper:]')"
                SN_RAILS_MASTER_KEY="$(echo RAILS_MASTER_KEY_${{ inputs.environment }} | tr '[:lower:]' '[:upper:]')"
                echo "secret names are: $SN_DEPLOY_KEY"
                echo "secret names are: $SN_DEPLOY_USER"
                echo "secret names are: $SN_RAILS_MASTER_KEY"
                echo "SN_DEPLOY_KEY=$SN_DEPLOY_KEY" >> $GITHUB_ENV
                echo "SN_DEPLOY_USER=$SN_DEPLOY_USER" >> $GITHUB_ENV
                echo "SN_RAILS_MASTER_KEY=$SN_RAILS_MASTER_KEY" >> $GITHUB_ENV
               
            - name: Write Secrets to Github env - not possible.
              run: |
                echo "CHECK_SSH_KEY=${{ vars[env.SN_DEPLOY_KEY] }}" >> $GITHUB_ENV
                
     
            - name: Checkout Repository
              uses: actions/checkout@v7
              with:
                fetch-depth: 0
                
  
            - name: Environment Variables to Github env
              run: |
                ./deploy/util/env_export_to_github_env.sh ${{ inputs.environment }}
       

            - name: print .env in new step
              run: |
                ./deploy/util/env_echo.sh ${{ inputs.environment }}
                echo "SSH_HOST=$HOST" >> $GITHUB_ENV
                echo "KNOWN_HOST=$KNOWN_HOST" >> $GITHUB_ENV
       
            
            - name: docker/metadata-action
              id: meta
              uses: docker/metadata-action@v6
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: ${{ inputs.version }}


            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.10.0
              with:
                ssh-private-key: ${{ secrets.DEPLOY_KEY_STAGING}}
                #ssh-private-key: ${{ env.SSH_KEY }}
                #ssh-private-key: ${{ secrets[env.SN_DEPLOY_KEY] }}
                
            
            - name: Verify SSH Connection
              run: |
                  export SSH_USER=${{ secrets[env.SN_DEPLOY_USER] }}
                  export SSH_KEY=${{ secrets[env.SN_DEPLOY_KEY] }}
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"


            
            - name: Execute Deployment
              run: |
                echo "Deploy version:\n ${{ inputs.version }} to ${{ inputs.environment }}"
                chmod +x deploy/deploy_environment.sh
                export RAILS_MASTER_KEY=${{ secrets[env.SN_RAILS_MASTER_KEY] }}
                export USER=${{ secrets[env.SN_DEPLOY_USER] }}
                export SSH_USER=${{ secrets[env.SN_DEPLOY_USER] }}
                export SSH_KEY=${{ secrets[env.SN_DEPLOY_KEY] }}
                ./deploy/deploy_environment.sh ${{ inputs.version }} ${{ inputs.environment }}
  