# names are short as they are prepended on gh actions
name: Staging
on:
  push:
    branches: [ main, update_devise_email_texts ]
    tags-ignore: [ '*' ]

env:
  SHA:  ${{ github.sha }}

jobs:
  defineversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.defineversion.outputs.version}}
    steps:
      - name: print github environment      
        run: |
          echo "---- github:\n${{ toJSON(github) }}"
      - id: defineversion
        run: echo "version=sha-${SHA:0:7}" >> "$GITHUB_OUTPUT"

  staging:
    needs: defineversion
    name: "Stag"
    # if: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/pipeline_02_structure.yml
    with:
      tags: type=sha
      push: true
      environment: staging
      version: ${{ needs.defineversion.outputs.version }}
      target: modhand-prod
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
      DEPLOY_MH_STAG_KEY: ${{ secrets.DEPLOY_MH_STAG_KEY }}
      DEPLOY_MH_STAG_USER: ${{ secrets.DEPLOY_MH_STAG_USER }}
      RAILS_MASTER_KEY_STAGING: ${{ secrets.RAILS_MASTER_KEY_STAGING }}
