
# build and (maybe) push docker image workflow called by  pipeline_02_structure.yml

name: Build and Push Image

on:
  workflow_call:
    secrets:
      rails_master_key:
        required: false
      nudge:
        required: false
      nudge_key:
        required: false
    inputs:
      tags:
        required: true
        type: string
      push:
        required: true
        type: boolean
      target:
        required: false
        type: string
        default: modhand-prod
      environment:
        required: false
        type: string
        default: staging


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Workflow Info
        run: |
          echo event_name ${{ github.event_name }}
          echo ref_type ${{ github.ref_type }}
          echo ref ${{ github.ref }}
          echo inputs tags ${{ inputs.tags }}
          echo inputs push ${{ inputs.push }}
      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker - PR
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ inputs.tags}}
      - name: Metadata Results
        run: |
           echo "---- tags:\n ${{ steps.meta.outputs.tags }}"
           echo "---- labels:\n ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ inputs.target }}
          build-args: RAILS_MASTER_KEY=${{ secrets.rails_master_key }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

