# names are short as they are pre-pended on gh actions
name: Production Pipeline
on:
  push:
    tags: [ '*' ]

jobs:
  production:
     name: P
     # this will not work as the ref is ref/tags/0...
     # if: github.ref == 'refs/heads/master'
     uses: ./.github/workflows/pipeline_02_structure.yml
     with:
       tags: type=ref,event=tag
       deploy_tag: ${{ github.ref_name }}
       push: true
       environment: production
     secrets:
       rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
       DEPLOY_MH_KEY: ${{ secrets.DEPLOY_MH_KEY }}
       DEPLOY_MH_USER: ${{ secrets.DEPLOY_MH_USER }}
       DEPLOY_MHIMI_KEY: ${{ secrets.DEPLOY_MHIMI_KEY }}
       DEPLOY_MHIMI_USER: ${{ secrets.DEPLOY_MHIMI_USER }}

