
# this is the general build and deploy pipeline definition.
# it is called with different paramters from the
# pl-start-* scripts.

name: "Pipeline"
on:
  workflow_call:
    secrets:
      rails_master_key:
        required: false
      RAILS_MASTER_KEY_STAGING:
        required: false
      DEPLOY_MH_STAG_KEY: 
        required: false
      DEPLOY_MH_STAG_USER:
        required: false
      DEPLOY_MH_KEY: 
        required: false
      DEPLOY_MH_USER: 
        required: false
      DEPLOY_MHIMI_KEY: 
        required: false
      DEPLOY_MHIMI_USER: 
        required: false


    inputs:
      tags:
        required: true
        type: string
      push:
        required: true
        type: boolean
      target:
        required: false
        type: string
        default: modhand-prod
      environment:
        required: false
        type: string
        default: staging

jobs:
  test_app:
    name: "1"
    uses: ./.github/workflows/pipeline_03_test_rails_app.yml
  
  test_system:
    name: "2"
    uses: ./.github/workflows/pipeline_03_test_system.yml

  code_quality:
    name: "3"
    uses: ./.github/workflows/pipeline_03_code_quality.yml

  build_and_push:
    needs: [test_app, test_system, code_quality]
    name: "4"
    uses: ./.github/workflows/pipeline_04_docker_build_and_push.yml
    with:
      tags: ${{ inputs.tags }}
      push: ${{ inputs.push }}
      target: ${{ inputs.target }}
      environment: ${{ inputs.environment }}
    secrets:
      rails_master_key: ${{ secrets.rails_master_key }}
  
  trigger-staging-deployment:
    needs: build_and_push
    name: "Deploy Staging"
    if: ${{ inputs.environment == 'staging' && inputs.push == true }}
    uses: ./.github/workflows/pipeline_05_deploy_to_staging.yml
    secrets: 
      DEPLOY_MH_STAG_KEY: ${{ secrets.DEPLOY_MH_STAG_KEY }}
      DEPLOY_MH_STAG_USER: ${{ secrets.DEPLOY_MH_STAG_USER }}
      RAILS_MASTER_KEY_STAGING: ${{ secrets.RAILS_MASTER_KEY_STAGING }}
  
  mh-production-deployment:
    needs: build_and_push
    name: "Deploy Production"
    if: ${{ inputs.environment == 'production'  && inputs.push == true }}
    uses: ./.github/workflows/pipeline_05_deploy_to_production.yml 
    inputs:
      host: 'module-handbook.f4.htw-berlin.de'
      known_host: 'module-handbook.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEo5BCmDcatOwixOtx2GCrtNbMFzBtOHjeh9+isNrf9'
      env_name: 'production'
    secrets:
      rails_master_key: ${{ secrets.rails_master_key }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_MH_KEY }}
      DEPLOY_USER: ${{ secrets.DEPLOY_MH_USER }}

  mh-imi-production-deployment:
    needs: build_and_push
    name: "Deploy Production"
    if: ${{ inputs.environment == 'production'  && inputs.push == true }}
    uses: ./.github/workflows/pipeline_05_deploy_to_production.yml 
    inputs:
      host: 'mh-imi.f4.htw-berlin.de'
      known_host: 'mh-imi.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrRpNEpcWrj53aPwPYjzFfj9hKYtUn8rEttOSQCCml'
      env_name: 'imi-production'
    
    secrets:
      rails_master_key: ${{ secrets.rails_master_key }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_MHIMI_KEY }}
      DEPLOY_USER: ${{ secrets.DEPLOY_MHIMI_USER }}

  info:
    name: Show Parameter
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo event_name ${{ github.event_name }}
          echo ref_type ${{ github.ref_type }}
          echo ref ${{ github.ref }}
          echo "----- inputs ------"
          echo "tags: ${{ inputs.tags }}"
          echo "push: ${{ inputs.push }}"
          echo "target: ${{ inputs.target }}"
          echo "environment: ${{ inputs.environment }}"