# names are short as they are pre-pended on gh actions
name: Production
on:
  push:
    branches: wf_matrix
    tags: [ '*' ]

env:
  TAG:  ${{ github.ref_name }}

jobs:

  defineversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.defineversion.outputs.version }}
    steps:
      - id: defineversion
        run: echo "version=${TAG}" >> "$GITHUB_OUTPUT"

  build-and-test:
    needs: defineversion
    name: Prod
    # this will not work as the ref is ref/tags/0...
    # if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/pipeline_02_structure.yml
    with:
      tags: type=ref,event=tag
      push: true
      deploy: false
      environment: production
      version: ${{ needs.defineversion.outputs.version }}
    secrets: 
      ssh_key: ${{ secrets.DEPLOY_KEY_PRODUCTION }}
      ssh_user: ${{ secrets.DEPLOY_USER_PRODUCTION }}
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY_PRODUCTION }}

  deploy_imi_production:
    needs: build-and-test
    name: "IMI"
    uses: ./.github/workflows/pipeline_05_deploy.yml
    with:
      environment: imi_production
      #version: ${{ needs.defineversion.outputs.version }}
      version: 0.2.27
    secrets: 
      ssh_key: ${{ secrets.DEPLOY_KEY_IMI_PRODUCTION }}
      ssh_user: ${{ secrets.DEPLOY_USER_IMI_PRODUCTION }}
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY_IMI_PRODUCTION }}

  deploy_production:
    needs: build-and-test
    name: "Deploy Production"
    uses: ./.github/workflows/pipeline_05_deploy.yml
    with:
      environment: production
      #version: ${{ needs.defineversion.outputs.version }}
      version: 0.2.27
    secrets: 
      ssh_key: ${{ secrets.DEPLOY_KEY_PRODUCTION }}
      ssh_user: ${{ secrets.DEPLOY_USER_PRODUCTION }}
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY_PRODUCTION }}
