
name: Post Deployment
# things that should be done after deployment

on:
    workflow_call:
      inputs:     
        version:
          required: true
          type: string

jobs:
  post_deployment_things:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production
        uses: ./.github/workflows/deploy_production.yml
        with:
          version: ${{ inputs.version }}
