name: Deploy

on:
    workflow_call:  # Triggered by the 02: Pipeline Structure workflow
      inputs:     
        version:
          required: true
          type: string
        environment:
          required: true
          type: string

      secrets:
        deploy_key: 
          required: true
        deploy_user:
          required: true
        rails_master_key:
          required: true


jobs:

    deploy-gen:
        runs-on: ubuntu-latest
        env:
            SSH_KEY: ${{ secrets.deploy_key }}
            SSH_USER: ${{ secrets.deploy_user }}
            SSH_HOST: ${{ inputs.host }}
            KNOWN_HOST: ${{ inputs.known_hosts }}
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
       
        steps:

            - name: Dynamic Secret Name Tryout
            # https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions
            # https://github.com/orgs/community/discussions/23473
              run: |
                echo "inputs.environment directly"
                echo inputs.environment
                echo "variable directly "
                echo "TEST_VARIABLE_STAGING 1 ${TEST_VARIABLE_STAGING} (prints nothing)"
                echo "TEST_VARIABLE_STAGING 2 ${{ vars.TEST_VARIABLE_STAGING }} (works)"

                echo "variable constructed"
                echo "TEST_VARIABLE_STAGING 3 ${{ vars[format('env.TEST_VARIABLE_{0}', inputs.environment)] }}"
                echo "TEST_VARIABLE_STAGING 4 ${{ vars['TEST_VARIABLE_STAGING'] }} (works!)"
                echo "TEST_VARIABLE_STAGING 5 ${{ vars[format('vars.TEST_VARIABLE_{0}', 'staging')] }}"
                echo "TEST_VARIABLE_STAGING 6 ${{ vars[format('vars.TEST_VARIABLE_{0}', 'STAGING')] }}"
                echo "TEST_VARIABLE_STAGING 7 ${{ vars[format('vars.TEST_VARIABLE_{0}', inputs.environment)] }}"
                echo "inputs.environment ${{ inputs.environment }}"
                VAR_NAME="TEST_VARIABLE_${{ inputs.environment }}"
                echo "VAR_NAME: ${VAR_NAME}"
                echo "TEST_VARIABLE_STAGING 4 ${{ vars['TEST_VARIABLE_STAGING'] }} (works!)"
                echo "env.VAR_NAME ${{ env.VAR_NAME }}"
                echo "TEST_VARIABLE_STAGING 6 ${{ vars[env.VAR_NAME] }}"

            
                echo "--- will not be printed"
                echo "secret constructed"
                echo ${{ env[format('secrets.TEST_{0}', inputs.environment)] }}
                echo "secret directly "
                echo ${{ secrets.TEST_STAGING }}

                echo " ---- done ---- "

          
            
            - name: Write to env Tryout
              run: |
                echo "TEST_NOT_FILTERED=HUHU" >> $GITHUB_ENV
            - name: Read from  env Tryout
              run: |
                echo "TEST_NOT_FILTERED 1: ${{ env.TEST_NOT_FILTERED }}"
                echo "TEST_NOT_FILTERED 2: $TEST_NOT_FILTERED"
                echo "this should be the same as having it declared with env:"
                echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
                echo "IMAGE_NAME2: $IMAGE_NAME"


            - name: Checkout Repository
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.10.0
              with:
                ssh-private-key: ${{ env.SSH_KEY }}
            
            - name: Verify SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"
            
            - name: docker/metadata-action
              id: meta
              uses: docker/metadata-action@v6
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: ${{ inputs.tags}}

            - name: Set Environment Variables
              run: |
                echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV

            - name: Execute Deployment
              run: |
                echo "Deploy version:\n ${{ inputs.version }} to "
                chmod +x deploy/deploy_environment.sh
                export RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
                ./deploy/deploy_environment.sh ${{ inputs.version }} ${{ inputs.environment }}
  