name: Deploy to Production

on:
    workflow_call:  # Triggered by the Build and Push workflow
      secrets:
        rails_master_key:
          required: true
        DEPLOY_KEY: 
          required: true
        DEPLOY_USER: 
          required: true
      inputs:
        host:
          required: true
          type: string
        known_host:
          required: true
          type: boolean
        env_name:
          required: false
          type: string
          default: production


jobs:
    deploy-production:
        name: "Deploy Production"
        runs-on: ubuntu-latest
        env:
          SSH_KEY: ${{ secrets.DEPLOY_MH_KEY }}
          SSH_USER: ${{ secrets.DEPLOY_MH_USER }}
          SSH_HOST: ${{ inputs.host }}
          KNOWN_HOST: ${{ inputs.known_host }}
          ENV_NAME: ${{ inputs.env_name }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ env.SSH_KEY }}
            
            - name: Verify SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"
              
            - name: Set Environment Variables
              run: |
                echo "RAILS_MASTER_KEY=${{ secrets.rails_master_key }}" >> $GITHUB_ENV

            - name: Execute Deployment
              run: |
                chmod +x deploy/production.sh
                ./deploy/production.sh ${{ env.ENV_NAME }}

   