name: Deploy

on:
    workflow_call:  # Triggered by the 02: Pipeline Structure workflow
      inputs:     
        version:
          required: true
          type: string
        host:
          required: true
          type: string
        environment:
          required: true
          type: string
        known_hosts:
          required: true
          type: string
      secrets:
        DEPLOY_KEY: 
          required: true
        DEPLOY_USER:
          required: true
        RAILS_MASTER_KEY:
          required: true


jobs:

    deploy:
        runs-on: ubuntu-latest
        env:
            SSH_KEY: ${{ secrets.DEPLOY_KEY }}
            SSH_USER: ${{ secrets.DEPLOY_USER }}
            SSH_HOST: ${{ inputs.host }}
            KNOWN_HOST: ${{ inputs.known_hosts }}
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
       
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set Up SSH
              uses: webfactory/ssh-agent@v0.10.0
              with:
                ssh-private-key: ${{ env.SSH_KEY }}
            
            - name: Verify SSH Connection
              run: |
                  ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH Connection Successful'"
            
            - name: docker/metadata-action
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: ${{ inputs.tags}}

            - name: Set Environment Variables
              run: |
                echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV

            - name: Execute Deployment
              run: |
                echo "Deploy version:\n ${{ inputs.version }} to "
                chmod +x deploy/deploy_environment.sh
                export RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
                ./deploy/deploy_environment.sh ${{ inputs.version }} ${{ inputs.environment }}
  