
# this is the general build and deploy pipeline definition.
# it is called with different paramters from the
# pl-start-* scripts.

name: "Pipeline"
on:
  workflow_call:
    secrets:
      rails_master_key:
        required: false
    inputs:
      tags:
        required: true
        type: string
      push:
        required: true
        type: boolean
      target:
        required: false
        type: string
        default: modhand-prod
      server:
        required: false
        type: string
        default: staging

jobs:
  test_app:
    name: Test
    uses: ./.github/workflows/pl-test-rails-app.yml

  build_and_push:
    needs: test_app   #### for now to get faster results on the builds
    name: Docker
    uses: ./.github/workflows/pl-build-and-push-image.yml
    with:
      tags: ${{ inputs.tags }}
      push: ${{ inputs.push }}
      target: ${{ inputs.target }}
      server: ${{ inputs.server }}
    secrets:
      rails_master_key: ${{ secrets.rails_master_key }}


  info:
    name: List Parameter
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo event_name ${{ github.event_name }}
          echo ref_type ${{ github.ref_type }}
          echo ref ${{ github.ref }}
          echo "----- inputs ------"
          echo "tags: ${{ inputs.tags }}"
          echo "push: ${{ inputs.push }}"
          echo "target: ${{ inputs.target }}"
          echo "target: ${{ inputs.server }}"
