name: Staging
on:
  push:
    branches: [ master ]
    tags-ignore: [ '*' ]

jobs:
  staging:
    name: Staging
    # if: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/master'}}
    uses: ./.github/workflows/pl-pipeline-definition.yml
    with:
      tags: type=sha
      push: true
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
