name: Test SSH

on:
  workflow_dispatch:
  push:
    branches: 'test_ssh'

jobs:
  mh-imi:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_MHIMI_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_MHIMI_USER }}
      SSH_HOST: 'mh-imi.f4.htw-berlin.de'
      KNOWN_HOST: 'mh-imi.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrRpNEpcWrj53aPwPYjzFfj9hKYtUn8rEttOSQCCml'
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"

  infrastructure:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_INF_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_INF_USER }}
      SSH_HOST: 'infrastructure.f4.htw-berlin.de'
      KNOWN_HOST: 'infrastructure.f4.htw-berlin.de ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFrJk3IjoJf61+rHU/ZMyD4ud488roXMJaa2NEeBiNruZGIw7k4YBLaZgCgfQNk+T/vzXTls+XIuY5S6rI8FD2I='
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"


  module-handbook-staging:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_MH_STAG_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_MH_STAG_USER }}
      SSH_HOST: 'module-handbook-staging.f4.htw-berlin.de'
      KNOWN_HOST: 'module-handbook-staging.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEo5BCmDcatOwixOtx2GCrtNbMFzBtOHjeh9+isNrf9'
  
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"


  module-handbook:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_MH_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_MH_USER }}
      SSH_HOST: 'module-handbook.f4.htw-berlin.de'
      KNOWN_HOST: 'module-handbook.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEo5BCmDcatOwixOtx2GCrtNbMFzBtOHjeh9+isNrf9'
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"

  progwebtec:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_PROGWEBTEC_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_PROGWEBTEC_USER }}
      SSH_HOST: 'progwebtec.f4.htw-berlin.de'
      KNOWN_HOST: 'progwebtec.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrRpNEpcWrj53aPwPYjzFfj9hKYtUn8rEttOSQCCml'
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"
     
  makesign:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.DEPLOY_MAKESIGN_KEY }}
      SSH_USER: ${{ secrets.DEPLOY_MAKESIGN_USER }}
      SSH_HOST: 'makesign.f4.htw-berlin.de'
      KNOWN_HOST: 'makesign.f4.htw-berlin.de ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWrRpNEpcWrj53aPwPYjzFfj9hKYtUn8rEttOSQCCml'
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}
      - name: Create Known Hosts File
        run: |
            echo $KNOWN_HOST > ~/.ssh/known_hosts
      - name: Test Connection
        run: |
          ssh $SSH_USER@$SSH_HOST "ls -lart"
             
                 