# this can be used to start the full pipeline from dev branches
# names are short as they are pre-pended on gh actions
name: Tryout Deployment
on:
  workflow_dispatch:
  push:
    branches: [ '*' ]

jobs:
  trigger-staging:
    name: "Tryout"
    uses: ./.github/workflows/pipeline_05_deploy_generic.yml
    with:
      version: sha-de197ac
      environment: 'staging'
