require 'application_system_test_case'

# If tests have the same name, all callbacks are called (see the example below).
# the following output was generated by adding the below lines to
# gems/devise-4.8.0/lib/devise/test/integration_helpers.rb:37

# def sign_in(resource, scope: nil)
#     puts "+++++ DEVISE INTEGRATION PID #{Process.pid} THR #{Thread.current.object_id} signing in #{resource.email} (#{resource.id})"
#     puts "+++++ from: #{caller[0]}"



# ok  (versioning✗)code/modulehandbook/modulehandbook # rails test test/system/devise-api/different_users/active_record_callback_test.rb
# Running via Spring preloader in process 72251
# require simplecov from rails script
# started SimpleCov
# require simplecov from test_helper
# Run options: --seed 2138
#
# # Running:
#
# +++++ DEVISE INTEGRATION PID 72251 THR 5760 signing in writer@mail.de (396417156)
# +++++ from: /Users/kleinen/mine/current/code/modulehandbook/modulehandbook/test/system/devise-api/different_users/active_record_callback_test.rb:6:in `block in <class:OneNameTest>'
# +++++ DEVISE INTEGRATION PID 72251 THR 5760 signing in editor@mail.de (217182653)
# +++++ from: /Users/kleinen/mine/current/code/modulehandbook/modulehandbook/test/system/devise-api/different_users/active_record_callback_test.rb:19:in `block in <class:OneNameTest>'
# Capybara starting Puma...
# * Version 5.5.2 , codename: Zawgyi
# * Min threads: 0, max threads: 4
# * Listening on http://127.0.0.1:55782
# .+++++ DEVISE INTEGRATION PID 72251 THR 5760 signing in writer@mail.de (396417156)
# +++++ from: /Users/kleinen/mine/current/code/modulehandbook/modulehandbook/test/system/devise-api/different_users/active_record_callback_test.rb:6:in `block in <class:OneNameTest>'
# +++++ DEVISE INTEGRATION PID 72251 THR 5760 signing in editor@mail.de (217182653)
# +++++ from: /Users/kleinen/mine/current/code/modulehandbook/modulehandbook/test/system/devise-api/different_users/active_record_callback_test.rb:19:in `block in <class:OneNameTest>'
# .
#
# Finished in 8.039309s, 0.2488 runs/s, 0.2488 assertions/s.
# 2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
# Coverage report generated for Unit Tests to /Users/kleinen/mine/current/code/modulehandbook/modulehandbook/coverage. 110 / 661 LOC (16.64%) covered.


class OneNameTest < ApplicationSystemTestCase
  setup do
    @user_writer = users(:writer)
    system_test_logout
    system_test_login(@user_writer.email, 'geheim12')
  end

  test 'editor is logged in as both setups are called, also the one below!' do
    visit root_path
    # also, @user_editor is defined.
    assert_text 'Logged in as '+@user_editor.email
  end
end

class OneNameTest < ApplicationSystemTestCase
  setup do
    @user_editor = users(:editor)
    system_test_logout
    system_test_login(@user_editor.email, 'geheim12')
  end

  test 'editor is logged in 2' do
    visit root_path
    assert_text 'Logged in as '+@user_editor.email
  end

end
